apiVersion: v1
kind: Pod
metadata: 
    name: sayyam-pod
    labels: 
      role: thisrole
spec:
    containers:
      - name: nginx
        image: nginx
        ports: 
        - name: nginx-web
          containerPort: 80
          protocol: TCP
      - name: Tomcat
        image: tomcat
        ports: 
        - name: tomcat-web
          containerPort: 8080
          protocol: TCP