apiVersion: v1
kind: Pod
metadata: 
    name: sayyam-pod
    labels: 
      role: thisrole
spec:
    containers:
      - name: nginx
          image: nginx
          port: 
            - containerPort: 80
              protocol: TCP
      - name: tomcat
          image: tomcat
          port: 
            - containerPort: 8080
              protocol: TCP